name: Good First Issue Candidate (C++)
description: Propose a candidate issue that may be suitable as a Good First Issue (C++)
title: "[GFI Candidate][C++]: "
labels: ["C++"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ---
        ## Maintainer Instructions (Not shown in final issue)

        This template is for proposing **Good First Issue candidates**, not guaranteed GFIs.

        - Markdown sections are **only visible to the form-filler**
        - Anything intended for contributors **must go in textarea fields**
        - Triage or maintainers may later apply the `good first issue` label

        Use this form to describe a **small, well-scoped, beginner-friendly task**.
        ---

  - type: markdown
    attributes:
      value: |
        ## What makes a good GFI candidate?
        - Narrow, self-contained change
        - Minimal architectural knowledge required
        - Easy to explain with links and examples
        - Safe refactors, docs, or small test improvements

        Avoid:
        - New core features
        - Large refactors
        - Multi-subsystem changes
        - Deep protocol or SDK knowledge

  - type: textarea
    id: intro
    attributes:
      label: 🆕🐥 Who this issue is for
      description: This text will appear in the final issue.
      value: |
        👋 **New contributors welcome!**

        This issue is intended as a **Good First Issue candidate** for contributors who are new to the **Hiero C++ SDK** or open source in general.

        You do not need deep knowledge of the codebase to get started. The goal is to help you learn the workflow, tooling, and contribution process while making a meaningful improvement.

    validations:
      required: true

  - type: textarea
    id: contribution_guide
    attributes:
      label: 🛠 How to contribute
      description: Step-by-step instructions shown to contributors.
      value: |
        ### Contribution Workflow

        1. **Fork the repository**
           Click the `Fork` button on GitHub to create your own copy.

        2. **Clone your fork**
        ```bash
        git clone https://github.com/<your-username>/<repo>.git
        cd <repo>
        ```

        3. **Add the upstream repository**
        ```bash
        git remote add upstream https://github.com/hiero-ledger/<repo>.git
        ```

        4. **Sync your local `main` branch**
        ```bash
        git pull upstream main
        ```

        5. **Create a feature branch**
        ```bash
        git checkout -b my-feature
        ```

        6. **Make your changes**, then stage them
        ```bash
        git add <file>
        ```

        7. **Commit with sign-off and GPG signing**
        ```bash
        git commit --signoff -S -m "Your commit message"
        ```

        8. **Push your branch**
        ```bash
        git push origin my-feature
        ```

        9. **Open a Pull Request**
        - Reference this issue in the PR description
        - Keep commits small and focused
        - Ensure tests pass

    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the issue
      description: Clearly describe the problem in beginner-friendly language.
      value: |
        ## 👾 Example (C++)

        The C++ implementation of `TokenAssociateTransaction` currently combines multiple responsibilities:
        parsing protobuf data, validating input, and constructing transaction objects.

        Example code:

        ```cpp
        void TokenAssociateTransaction::initFromSourceTransactionBody()
        {
          const proto::TransactionBody transactionBody = getSourceTransactionBody();

          if (!transactionBody.has_tokenassociate())
          {
            throw std::invalid_argument("Transaction body doesn't contain TokenAssociate data");
          }

          const proto::TokenAssociateTransactionBody& body = transactionBody.tokenassociate();

          if (body.has_account())
          {
            mAccountId = AccountId::fromProtobuf(body.account());
          }

          for (int i = 0; i < body.tokens_size(); ++i)
          {
            mTokenIds.push_back(TokenId::fromProtobuf(body.tokens(i)));
          }
        }
        ```

        While correct, this structure can be difficult for new contributors to follow.

    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe a possible approach. This does not need to be perfect.
      value: |
        Refactor `TokenAssociateTransaction` to separate responsibilities:

        - Extract protobuf parsing into a helper function
        - Use clearer method names for intent
        - Keep external behavior unchanged

        This improves readability and maintainability without introducing new features.

    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps
      description: Break the work into concrete, beginner-friendly steps.
      value: |
        - [ ] Identify parsing logic in `TokenAssociateTransaction`
        - [ ] Extract parsing into `parseTokenAssociateBody()`
        - [ ] Keep validation and submission logic unchanged
        - [ ] Run existing tests
        - [ ] Update documentation or comments if needed

        Example helpers:
        ```cpp
        void parseTokenAssociateBody(const proto::TokenAssociateTransactionBody& body);
        ```

    validations:
      required: true
